In [66]:
import pandas as pd

In [67]:
paper = pd.read_csv("13_10_25_screening_v3.csv", on_bad_lines="skip", encoding="ISO-8859-1")
paper = paper[paper["inclusion"] == 1]
paper.head()

,ï»¿title,doi,inclusion,reasoning_inclusion,score_clarity_research_design,score_methodological_rigor,score_validation_methods,reasoning_score,cited_by_count
1,Aegis:An Advanced LLM-Based Multi-Agent for In...,10.48550/ARXIV.2410.12475,1.0,1. **EC1 Evaluation:**\n- The article focuses ...,1.0,1.0,1.0,"{\n ""reasoning"": ""The paper presents a clear ...",0.0
2,AI-Driven Multimodal Analysis for Innovations ...,10.20944/preprints202410.0099.v1,1.0,The title and abstract indicate that the paper...,1.0,1.0,1.0,"{\n ""reasoning"": ""The manuscript presents a c...",0.0
3,An Industry Application of Secure Augmentation...,10.3390/a18070414,1.0,The paper discusses the integration of Large L...,2.0,2.0,2.0,"{\n ""reasoning"": ""**QA1 â Clarity of resear...",0.0
4,BMW Agents -- A Framework For Task Automation ...,10.48550/ARXIV.2406.20041,1.0,Evaluation against exclusion criteria: **EC1:*...,2.0,1.0,1.0,"{\n ""reasoning"": ""The paper presents a wellâ...",0.0
5,Computer Vision for Automated Robotic Device D...,10.53846/goediss-10856,1.0,The paper includes Large Language Models (LLMs...,2.0,2.0,2.0,"{\n ""reasoning"": ""The dissertation presents a...",0.0

In [68]:
# get average scores
paper['average_score'] = paper[['score_clarity_research_design', 'score_methodological_rigor', 'score_validation_methods']].mean(axis=1)

paper.head()

,ï»¿title,doi,inclusion,reasoning_inclusion,score_clarity_research_design,score_methodological_rigor,score_validation_methods,reasoning_score,cited_by_count,average_score
1,Aegis:An Advanced LLM-Based Multi-Agent for In...,10.48550/ARXIV.2410.12475,1.0,1. **EC1 Evaluation:**\n- The article focuses ...,1.0,1.0,1.0,"{\n ""reasoning"": ""The paper presents a clear ...",0.0,1.000000
2,AI-Driven Multimodal Analysis for Innovations ...,10.20944/preprints202410.0099.v1,1.0,The title and abstract indicate that the paper...,1.0,1.0,1.0,"{\n ""reasoning"": ""The manuscript presents a c...",0.0,1.000000
3,An Industry Application of Secure Augmentation...,10.3390/a18070414,1.0,The paper discusses the integration of Large L...,2.0,2.0,2.0,"{\n ""reasoning"": ""**QA1 â Clarity of resear...",0.0,2.000000
4,BMW Agents -- A Framework For Task Automation ...,10.48550/ARXIV.2406.20041,1.0,Evaluation against exclusion criteria: **EC1:*...,2.0,1.0,1.0,"{\n ""reasoning"": ""The paper presents a wellâ...",0.0,1.333333
5,Computer Vision for Automated Robotic Device D...,10.53846/goediss-10856,1.0,The paper includes Large Language Models (LLMs...,2.0,2.0,2.0,"{\n ""reasoning"": ""The dissertation presents a...",0.0,2.000000

In [69]:
# get average across all papers
average_clarity = paper['score_clarity_research_design'].mean(axis=0)
average_rigor = paper['score_methodological_rigor'].mean(axis=0)
average_validation = paper['score_validation_methods'].mean(axis=0)
average_overall = paper['average_score'].mean(axis=0)

print(f"Average clarity score: {average_clarity}")
print(f"Average rigor score: {average_rigor}")
print(f"Average validation score: {average_validation}")
print(f"Average overall score: {average_overall}")

Average clarity score: 1.7586206896551724
Average rigor score: 1.5517241379310345
Average validation score: 1.5172413793103448
Average overall score: 1.6091954022988508

In [73]:
paper_qa = paper[paper['average_score'] >= 1.0]
difference = len(paper) - len(paper_qa)
print(f"Dropped {difference} papers below quality threshold")
dropped_papers = paper[paper['average_score'] < 1.0]
print(f"\n{dropped_papers["ï»¿title"].to_string(index=False)}")

Dropped 1 papers below quality threshold
Dropped papers:
Physical AI Agents: Integrating Cognitive Intel...

In [74]:
# drop papers with any score below 1
paper_qa_strict = paper[(paper['score_clarity_research_design'] >= 1.0) &
                        (paper['score_methodological_rigor'] >= 1.0) &
                        (paper['score_validation_methods'] >= 1.0)]
difference_strict = len(paper) - len(paper_qa_strict)
print(f"Dropped {difference_strict} papers below strict quality threshold")
dropped_papers_strict = paper[~paper.index.isin(paper_qa_strict.index)]
print(f"\n{dropped_papers_strict["ï»¿title"].to_string(index=False)}")

Dropped 1 papers below strict quality threshold

Physical AI Agents: Integrating Cognitive Intel...